services:
  # Layanan Web untuk Aplikasi Laravel
  - type: web
    name: qc-check-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan storage:link
      php artisan migrate --force
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: psql
          name: qc-check-database
          property: host
      - key: DB_PORT
        fromService:
          type: psql
          name: qc-check-database
          property: port
      - key: DB_DATABASE
        fromService:
          type: psql
          name: qc-check-database
          property: database
      - key: DB_USERNAME
        fromService:
          type: psql
          name: qc-check-database
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: qc-check-database
          property: password

  # Layanan Database PostgreSQL
  - type: psql
    name: qc-check-database
    plan: free
    postgresMajorVersion: 14
    ipAllowList: []